dist: trusty
sudo: false

git:
  depth: 8

branches:
  only:
    - master

language: python

python:
  - "2.7"

env:
  - CODECOV_TOKEN=f0d12df0-9687-40ac-b2f6-3e626edf3f85

install:
  - pip install -U tox

script:
  - tox
